---
# Role metadata for oracle_cloud_automation
galaxy_info:
  role_name: oracle_cloud_automation
  author: Oracle Cloud Automation Team
  description: Complete Oracle Cloud Infrastructure Always Free tier automation
  company: Open Source
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - oracle
    - cloud
    - automation
    - database
    - terraform
    - infrastructure

dependencies: []

# Role supports all standard tags
allow_duplicates: false