---
# Oracle Cloud Infrastructure Provisioning Playbook
# ALWAYS FREE TIER PROTECTION ALWAYS FREE TIER PROTECTION: Infrastructure-only deployment
- name: Provision Oracle Cloud Infrastructure Only
  hosts: localhost
  gather_facts: true
  vars:
    deployment_log: "{{ logs_dir }}/infrastructure-{{ ansible_date_time.epoch }}.log"

  tasks:
    - name: Display Infrastructure Provisioning Banner
      ansible.builtin.debug:
        msg: |
          +------------------------------------------------------------------+
          |           Oracle Cloud Infrastructure Provisioning              |
          |              ALWAYS FREE TIER PROTECTION ALWAYS FREE TIER PROTECTION ALWAYS FREE TIER PROTECTION                  |
          |                                                                  |
          |  This playbook provisions ONLY cloud infrastructure using       |
          |  Terraform with Always Free tier resources.                     |
          |                                                                  |
          |  Resources created:                                              |
          |  • Oracle Autonomous Database (1 OCPU, 20GB)                    |
          |  • Object Storage bucket (20GB limit)                           |
          |  • VCN and networking components                                 |
          |                                                                  |
          |  [COST] Cost: $0.00 (Always Free tier)                              |
          +------------------------------------------------------------------+

    # Prerequisites check
    - name: Check prerequisites for infrastructure provisioning
      block:
        - name: Verify Terraform is available
          ansible.builtin.command: "{{ local_bin_dir }}/terraform version"
          register: terraform_check
          failed_when: terraform_check.rc != 0
          changed_when: false

        - name: Verify OCI CLI is available
          ansible.builtin.command: "{{ ansible_env.HOME }}/.local/bin/oci --version"
          register: oci_check
          failed_when: oci_check.rc != 0
          changed_when: false

        - name: Check OCI configuration
          ansible.builtin.stat:
            path: "{{ oci_config_dir }}/config"
          register: oci_config
          failed_when: not oci_config.stat.exists

        - name: Verify terraform.tfvars exists
          ansible.builtin.stat:
            path: "{{ config_dir }}/terraform.tfvars"
          register: tfvars_check
          failed_when: not tfvars_check.stat.exists

        - name: Display prerequisites validation
          ansible.builtin.debug:
            msg: "[OK] All prerequisites validated successfully"
      rescue:
        - name: Prerequisites validation failed
          ansible.builtin.fail:
            msg: |
              [ERROR] Prerequisites validation failed!
              Please ensure:
              - Terraform is installed in {{ local_bin_dir }}
              - OCI CLI is installed and configured
              - terraform.tfvars file exists in {{ config_dir }}

              Run setup-environment.yml first to install prerequisites.

    # Environment setup (minimal - just variables)
    - name: Load environment variables
      ansible.builtin.include_vars: "{{ ansible_dir }}/group_vars/all.yml"
      when: ansible_dir is defined

    - name: Set default paths if not defined
      ansible.builtin.set_fact:
        local_bin_dir: "{{ ansible_env.HOME }}/.local/bin"
        config_dir: "{{ ansible_dir }}/../"
        terraform_dir: "{{ ansible_dir }}/../terraform"
        logs_dir: "{{ ansible_dir }}/../logs"
        oci_config_dir: "{{ ansible_env.HOME }}/.oci"
      when: local_bin_dir is not defined

    # Main infrastructure provisioning
    - name: "Phase 1: Provision Cloud Infrastructure"
      ansible.builtin.include_tasks: tasks/provision-infrastructure.yml
      tags: [infrastructure, terraform]

    # Display completion message
    - name: Display infrastructure provisioning completion
      ansible.builtin.debug:
        msg: |
          +------------------------------------------------------------------+
          |            [SUCCESS] INFRASTRUCTURE PROVISIONED! [SUCCESS]                    |
          |                                                                  |
          |  [OK] Oracle Cloud infrastructure is ready                        |
          |  [OK] Database and storage resources created                      |
          |  [OK] Networking components configured                            |
          |                                                                  |
          |  [COST] Cost: $0.00 (Always Free tier)                              |
          |                                                                  |
          |  Next Steps:                                                     |
          |  • Run configure-database tasks for app setup                   |
          |  • Or use deploy-complete-suite.yml for full deployment         |
          |                                                                  |
          |  Infrastructure outputs saved in Terraform state                |
          +------------------------------------------------------------------+
