-- Generated by Ansible - Package Validation Script
-- Timestamp: 2025-10-16T10:45:22Z
-- Environment: development

WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE
SET SERVEROUTPUT ON SIZE UNLIMITED
SET PAGESIZE 1000
SET LINESIZE 200
SET VERIFY OFF
SET FEEDBACK ON

PROMPT ====================================================================
PROMPT Package Validation Report
PROMPT ====================================================================

-- Package Status Summary
SELECT 
    object_type,
    status,
    COUNT(*) as count
FROM user_objects 
WHERE object_type IN ('PACKAGE', 'PACKAGE BODY')
GROUP BY object_type, status
ORDER BY object_type, status;

-- Detailed Package Information
PROMPT
PROMPT Detailed Package Status:
PROMPT ------------------------

SELECT 
    object_name,
    object_type,
    status,
    TO_CHAR(last_ddl_time, 'YYYY-MM-DD HH24:MI:SS') as last_modified
FROM user_objects 
WHERE object_type IN ('PACKAGE', 'PACKAGE BODY')
ORDER BY object_type, object_name;

-- Invalid Objects Report
PROMPT
PROMPT Invalid Objects (if any):
PROMPT -------------------------

SELECT 
    object_name,
    object_type,
    status
FROM user_objects 
WHERE status != 'VALID'
AND object_type IN ('PACKAGE', 'PACKAGE BODY', 'FUNCTION', 'PROCEDURE')
ORDER BY object_type, object_name;

-- Compilation Errors
PROMPT
PROMPT Compilation Errors (if any):
PROMPT ----------------------------

SELECT 
    name,
    type,
    line,
    position,
    text as error_message
FROM user_errors
WHERE type IN ('PACKAGE', 'PACKAGE BODY')
ORDER BY name, type, line;

-- Final Validation
DECLARE
    v_valid_count NUMBER;
    v_total_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_total_count
    FROM user_objects
    WHERE object_type IN ('PACKAGE', 'PACKAGE BODY');
    
    SELECT COUNT(*)
    INTO v_valid_count
    FROM user_objects
    WHERE object_type IN ('PACKAGE', 'PACKAGE BODY')
    AND status = 'VALID';
    
    DBMS_OUTPUT.PUT_LINE('====================================================================');
    DBMS_OUTPUT.PUT_LINE('VALIDATION SUMMARY');
    DBMS_OUTPUT.PUT_LINE('====================================================================');
    DBMS_OUTPUT.PUT_LINE('Total Packages: ' || v_total_count);
    DBMS_OUTPUT.PUT_LINE('Valid Packages: ' || v_valid_count);
    DBMS_OUTPUT.PUT_LINE('Invalid Packages: ' || (v_total_count - v_valid_count));
    
    IF v_valid_count = v_total_count AND v_total_count > 0 THEN
        DBMS_OUTPUT.PUT_LINE('Status: ✅ ALL PACKAGES VALID');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Status: ❌ VALIDATION ISSUES DETECTED');
    END IF;
    DBMS_OUTPUT.PUT_LINE('====================================================================');
END;
/

EXIT;